"use client"


import React, { useEffect, useState } from "react";
//GlobalStyle
import GlobalStyle from "./styles/GlobalStyle";
//Import Pages
import Nav from "./components/Nav";

//Animation
import { AnimatePresence } from "framer-motion";
import ScrollToTop from "./components/ScrollToTop";
//Router
import { changeColor } from "./components/theme/changeColor";
import Footer from "./components/Footer";
//Google analytics
import ReactGA from "react-ga";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  

  const [colorSchemeType, setColorSchemeType] = useState("light");


    // This effect triggers the scroll after navigation and animation completes
    useEffect(() => {
      const scrollToTop = () => {
        window.scrollTo({ top: 0, behavior: "smooth" });
      };

    // Call scrollToTop after a slight delay (to ensure animation completes)
    const timeout = setTimeout(() => {
      scrollToTop();
    }, 500); // Adjust this delay to match the exit animation duration

    return () => clearTimeout(timeout); // Cleanup the timeout
  }, [location]); // Runs when location (path) changes

  

  const handleBgClick = (evt) => {
    const isNavLink = evt.target.closest('a')
    const isButton = evt.target.closest('button')
    const isIcon = evt.target.closest('[data-icon="true"]');  // Use the data attribute to identify the icon    
    if(!isNavLink && !isButton && !isIcon) {
    setColorSchemeType("light");
    changeColor("light");
    // doRippleEffect(evt);
    // setTimeout(() => {
    //   doRippleEffect(evt);
    // }, 240);
  };
  };

  useEffect(() => {
    if (colorSchemeType === "light") {
      // change color will pick a new light color
      changeColor("light");
    } else {
      changeColor("dark");
    }
  }, [colorSchemeType]);
  

  return (
    <html lang="en">
       <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.11/lottie.min.js"></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

    <meta charset="utf-8" />

    <link rel="icon" href="/favicon-16x16.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="design and create" />
    <link rel="icon" href="/favicon-16x16.png" />
    <meta property="og:image" content="%PUBLIC_URL%/localImage.jpg" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200;0,400;0,600;0,700;0,800;1,200;1,400;1,800&family=Lora&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;700&family=Karla:wght@600&display=swap"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Jersey+20+Charted&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet" />

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> 
<link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap" rel="stylesheet" />

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />   
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
      <style jsx global>{`
          .material-symbols-outlined {
            font-variation-settings:
              'FILL' 0,
              'wght' 400,
              'GRAD' 0,
              'opsz' 24;
          }
        `}</style>
    <title>antbalsamo</title>
  </head>
      <body>
      
    <div className="App" onClick={(evt) => handleBgClick(evt)}>
      {/* <ScrollToTop> */}
        <GlobalStyle />
        <Nav
          colorSchemeType={colorSchemeType}
          setColorSchemeType={setColorSchemeType}
        />

        <div style={{ marginTop: "9vh" }}>
          <AnimatePresence exitBeforeEnter>
          
            {children}
          </AnimatePresence>
        </div>
        <Footer />
      {/* </ScrollToTop> */}
    </div>
     </body>
    </html>
  );
};

